language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - Gemfile
  - gemfiles/rspec-3.0.x.gemfile
  - gemfiles/rspec-3.1.x.gemfile
  - gemfiles/rspec-3.2.x.gemfile
script:
  - bundle exec rake
